### ISSUE TITLE
How to tune on X86 cpu?

### ISSUE THREAD

**Issue by catmaohphp** [KnowingNothing/AMOS#2]
Hi, Thanks for sharing your excellent work! I'm trying to perform auto-tensorization on x86 CPUs. Is there any tutorial about how to tune on this platform? I tried to modify the script that was originally designed for conv2d on Tensor Core, but it results in no valid solution. All I have is  "LLVM ERROR: Do not know how to split the result of this operator!". I also ran the 6th test case of  "tests/python/auto_tensorize/test_auto_schedule.py", and it works correctly. So I think the problem is not about the code generation procedure.  Environment:  Intel(R) Xeon(R) Gold 6314U CPU,  LLVM 8.0.0 , gcc 9.3.0.

**Comment by KnowingNothing** [comment]
Can you try [this file](https://github.com/KnowingNothing/AMOS/blob/amos-opensource/tutorials/auto_tensorize/mapping_ops/explore_mapping_conv2d_u8s8s32_avx512.py). It tunes conv2d with AVX-512 VNNI instruction.

**Comment by catmaohphp** [comment]
It works! Thank you for your quick response!
